"""
Minor Planet Center (MPC) 80-Column Observation Export Engine.
Generates strict, standards-compliant MPC observation records for minor planets, comets, and NEAs.
"""

from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional
from astrimetrique.utils.coordinates import datetime_to_fractional_day, format_dec, format_ra


@dataclass
class MPCObservation:
    """An astrometric observation record for MPC submission."""
    designation: str  # Permanent or provisional designation (e.g. '99942' or '2024 AB')
    utc_time: datetime  # Observation time in UTC
    ra_deg: float  # Right Ascension in J2000 decimal degrees
    dec_deg: float  # Declination in J2000 decimal degrees
    mag: Optional[float] = None  # Observed magnitude
    band: str = "R"  # Photometric band (e.g. 'V', 'R', 'G', 'C')
    obs_code: str = "500"  # 3-character observatory code
    is_discovery: bool = False  # Set '*' discovery flag
    note1: str = " "  # Optional note code
    note2: str = "C"  # Mode (e.g., 'C' for CCD)
    catalog_code: str = "Gaia3"  # Reference star catalog


@dataclass
class MPCObservatoryHeader:
    """Header information for MPC email / web report submission."""
    cod: str = "500"  # Observatory code
    con: str = "Astrimetrique Astrometric Observer"  # Contact / Observer name
    obs: str = "A. Observer"  # Observers
    mea: str = "A. Observer"  # Measurers
    tel: str = "0.4m f/8 Reflector + CCD"  # Telescope info
    net: str = "Gaia-DR3"  # Star catalog used
    ack: str = "MPC Report generated by Astrimetrique"


def format_mpc_designation(desig: str) -> str:
    """
    Format designation for columns 1-12.
    If 5 characters or fewer, left-align in cols 1-5 or right-align if numbered.
    """
    clean = desig.strip()
    if clean.isdigit():
        # Numbered asteroid: right-align in 5 characters
        return f"{int(clean):5d}"
    else:
        # Provisional or custom: padded to 12 chars
        if len(clean) <= 7:
            # e.g., '2024 AB' or 'K24A00B'
            return f"     {clean:<7}"
        return f"{clean:<12}"[:12]


def format_mpc_80_col(obs: MPCObservation) -> str:
    """
    Format a single MPCObservation into the strict 80-column line format.
    Column index layout (1-indexed):
    01-05: Numbered asteroid designation or 01-12 provisional designation
    13: Discovery asterisk '*'
    14: Note 1
    15: Note 2 ('C' for CCD)
    16-32: UTC Date 'YYYY MM DD.ddddd'
    33-44: RA (J2000) 'HH MM SS.ss'
    45-56: Dec (J2000) '+DD MM SS.s'
    57-65: Blank
    66-71: Magnitude and Band '18.2 R'
    72-77: Blank / Catalog
    78-80: Observatory Code
    """
    # 1-12: Designation
    desig_str = format_mpc_designation(obs.designation)
    if len(desig_str) < 12:
        desig_str = f"{desig_str:<12}"

    # 13: Discovery flag
    disc_char = "*" if obs.is_discovery else " "

    # 14: Note 1
    n1_char = obs.note1[0] if obs.note1 else " "

    # 15: Note 2
    n2_char = obs.note2[0] if obs.note2 else "C"

    # 16-32: UTC Date (17 chars)
    # datetime_to_fractional_day produces 'YYYY MM DD.ddddd' (16 chars)
    # Preceded by a space in col 16 -> ' YYYY MM DD.ddddd'
    date_str = f" {datetime_to_fractional_day(obs.utc_time)}"

    # 33-44: RA (12 chars: ' HH MM SS.ss')
    ra_str = f" {format_ra(obs.ra_deg, precision=2)}"

    # 45-56: Dec (12 chars: '+DD MM SS.s')
    dec_str = f" {format_dec(obs.dec_deg, precision=1)}"

    # 57-65: Blank (9 chars)
    blank_57_65 = " " * 9

    # 66-71: Magnitude & Band (6 chars e.g. '14.5 R' or '      ')
    if obs.mag is not None:
        band_char = obs.band[0] if obs.band else "R"
        mag_str = f"{obs.mag:4.1f} {band_char}"
        if len(mag_str) < 6:
            mag_str = f"{mag_str:>6}"
    else:
        mag_str = " " * 6

    # 72-77: Blank (6 chars)
    blank_72_77 = " " * 6

    # 78-80: Observatory code (3 chars)
    obs_code_str = f"{obs.obs_code:>3}"[:3]

    line = (
        f"{desig_str[:12]}"
        f"{disc_char}"
        f"{n1_char}"
        f"{n2_char}"
        f"{date_str[:17]}"
        f"{ra_str[:12]}"
        f"{dec_str[:12]}"
        f"{blank_57_65}"
        f"{mag_str[:6]}"
        f"{blank_72_77}"
        f"{obs_code_str}"
    )

    # Guarantee exact 80 characters
    if len(line) < 80:
        line = line.ljust(80)
    elif len(line) > 80:
        line = line[:80]

    return line


def generate_mpc_report(
    observations: List[MPCObservation],
    header: Optional[MPCObservatoryHeader] = None,
) -> str:
    """
    Generate a full MPC formatted submission report containing header block
    and 80-column observation lines.
    """
    hdr = header or MPCObservatoryHeader()
    lines = [
        f"COD {hdr.cod}",
        f"CON {hdr.con}",
        f"OBS {hdr.obs}",
        f"MEA {hdr.mea}",
        f"TEL {hdr.tel}",
        f"NET {hdr.net}",
        f"ACK {hdr.ack}",
        "--- 80-column observations ---",
    ]

    for obs in observations:
        lines.append(format_mpc_80_col(obs))

    lines.append("")  # Trailing newline
    return "\n".join(lines)
